### ISSUE TITLE
training & testing?

### ISSUE THREAD

**Issue by ahundt** [titu1994/Fully-Connected-DenseNets-Semantic-Segmentation#1]
Have you trained and tested with this? I don't see anything to load a semantic segmentation dataset.

**Comment by titu1994** [comment]
Not yet. I just implemented the model from the paper. I still have to see if the implementation is currently correct and then train it on some segmentation dataset.

**Comment by ahundt** [comment]
Cool, thanks for the update. I'm curious if simply tweaking your other [densenet](https://github.com/titu1994/DenseNet) implementation to use atrous convolutions could be more effective than the method in the tiramisu paper. I'm planning on doing this with resnet as detailed in this [keras-resnet issue](https://github.com/raghakot/keras-resnet/issues/23) first then might try it on densenets as well. Also there are some links to code in that issue that can load the camvid dataset which may save you time.
