### ISSUE TITLE
Data and/or example?

### ISSUE THREAD

**Issue by Timonzimm** [titu1994/Fully-Connected-DenseNets-Semantic-Segmentation#10]
Do you have any dataset and/or working example to use the given model? I am trying to use this on the CamVid dataset used in the original paper, without success..

**Comment by titu1994** [comment]
I haven't used it myself yet. I am going to be making a lot of corrections in the code in a few days though, since the current implementation is not exactly according to the paper.

**Comment by titu1994** [comment]
I haven't used it myself yet. I am going to be making a lot of corrections in the code in a few days though, since the current implementation is not exactly according to the paper.
