### ISSUE TITLE
Deprecated function call warnings with Keras 2.x.x

### ISSUE THREAD

**Issue by martinsand** [titu1994/Fully-Connected-DenseNets-Semantic-Segmentation#13]
When using newer versions of Keras, the DenseNet implementation here raises some warnings due to deprecation of some of the Keras calls used. It still works for now, but the Keras wraning states, that from 08/2017, it won't.

**Comment by titu1994** [comment]
There are a few bugs in Keras 2 at the moment. One of them is that concatenate is not working exactly like merge with mode concat, which DenseNet needs.

I will update the code when Keras 2 stabilizes, perhaps by the time it is merged with Tensorflow it will remove these bugs. At that point I will convert the code to the new API.

**Comment by martinsand** [comment]
Thank you, for explaining this for me. 
You should probably change the readme stating Keras requirement from 'Keras 1.2.2+' to 'Keras 1.2.2' until further compatibility is ensured.

**Comment by titu1994** [comment]
Yup, will do that in some time.
