### ISSUE TITLE
NameError: name 'DenseNetFCN' is not defined

### ISSUE THREAD

**Issue by MinuteswithMetrics** [titu1994/Fully-Connected-DenseNets-Semantic-Segmentation#15]
I get the following code when I try to run the script.

`NameError                                 Traceback (most recent call last)
<ipython-input-16-7219af46f3d8> in <module>()
      1 import densenet_fc as dc
      2 
----> 3 model = DenseNetFCN((64, 64, 3), nb_dense_block=5, growth_rate=16,
      4                         nb_layers_per_block=4, upsampling_type='upsampling', classes=1)

NameError: name 'DenseNetFCN' is not defined`

**Comment by titu1994** [comment]
You should use the DenseNet repository that I have. It has the updated version of this model. 

As to your issue, you import densenet_fc as dc, so you should write dc.DenseNetFCN(..)

**Comment by MinuteswithMetrics** [comment]
Thank you!!!!
