### ISSUE TITLE
Minor bug when using tensorflow backend

### ISSUE THREAD

**Issue by samtzai** [titu1994/Fully-Connected-DenseNets-Semantic-Segmentation#2]
depth_to_scale_tf function does not concatenate channels appropriately.
Line 48 at layers.py:
Xc = tf.split(3, 3, input) 
should be replaced by: 
Xc = tf.split(3, channels, input)

**Comment by titu1994** [comment]
Oh thanks! I have not tested the Tensorflow implementation yet so thanks for the corrections.

If you could add a PR it would be great, so that you can be given credit.
