### ISSUE TITLE
Average Pooling should be Max Pooling?

### ISSUE THREAD

**Issue by ahundt** [titu1994/Fully-Connected-DenseNets-Semantic-Segmentation#6]
It looks like the transition_down_block uses AveragePooling2D when it should be using MaxPooling2D as specified in the paper 3.3. Semantic Segmentation Architecture.

https://github.com/titu1994/Fully-Connected-DenseNets-Semantic-Segmentation/blob/master/densenet_fc.py#L75

Though perhaps that's worth making configurable with a flag.

**Comment by titu1994** [comment]
Hmm true. I overlooked the pooling method in the original implementation. Could you add a PR if you are free ? Or I will update in a few days.
